/**
 * Smart PHP Calendar
 *
 * Copyright (c) 2012 Yasin Dagli, Smart PHP Calendar, All rights reserved.
 *
 * This file is protected by international laws. Reverse engineering this file is strictly prohibited.
 */
$(function(){SPC.Object={};SPC.Object.length=function(a){var b=0,d;for(d in a)a.hasOwnProperty(d)&&b++;return b};SPC.Array={};SPC.Array.end=function(a){return a[a.length-1]};SPC.Array.unset=function(a,b){var d=a.slice(0,b),c=a.slice(b+1);return d.concat(c)};SPC.Array.foreach=function(a,b){var d;if(a instanceof Array)for(var c=0,e=a.length;c<e&&!(d=b(c,a[c]),!1===d);c++);else for(c in a)if(d=b(c,a[c]),!1===d)break;return a};SPC.Array.arraySearch=function(a,b,d){var c=0;if(d)for(;c<b.length;c++){if(b[c]===
a)return c}else for(;c<b.length;c++)if(b[c]==a)return c;return!1};SPC.isset=function(a){return"undefined"===typeof a?!1:!0};SPC.Array.multiply=function(a,b){for(var d=[],c=0;c<b;c++)d.push(a);return d};SPC.String={};SPC.String.sprinf=function(a,b){var d=0;return a.replace(/%s/g,function(){return b[d++]})};SPC.String.uCFirst=function(a){var b=a.split(" ");SPC.Array.foreach(b,function(a,c){b[a]=c.substr(0,1).toUpperCase()+c.substr(1)});return b.join(" ")};SPC.Date={};SPC.Date.dateConverter={};SPC.Date.dateConverter.padZeroLeft=
function(a){return 10>a?"0"+a:""+a};SPC.Date.dateConverter.getDatePickerDateFormat=function(){switch(SPC.userPrefs.calendar.shortdate_format){case "n/j/Y":return"m/d/yy";case "j/n/Y":return"d/m/yy";case "Y-n-j":return"yy-mm-dd"}};SPC.Date.dateConverter.coreToUser=function(a){if(""==a)return"";var b=a.split("-");coreDay=parseInt(b[2],10);coreMonth=parseInt(b[1],10);coreYear=b[0];b=SPC.userPrefs.calendar.shortdate_format;return"n/j/Y"==b?coreMonth+"/"+coreDay+"/"+coreYear:"j/n/Y"==b?coreDay+"/"+coreMonth+
"/"+coreYear:"Y-n-j"==b?a:!1};SPC.Date.dateConverter.userToCore=function(a){if(""==a)return"";var b=SPC.userPrefs.calendar.shortdate_format;"n/j/Y"==b?(a=a.split("/"),coreDay=SPC.Date.dateConverter.padZeroLeft(Number(a[1])),coreMonth=SPC.Date.dateConverter.padZeroLeft(Number(a[0])),coreYear=a[2]):"j/n/Y"==b?(a=a.split("/"),coreDay=SPC.Date.dateConverter.padZeroLeft(Number(a[0])),coreMonth=SPC.Date.dateConverter.padZeroLeft(Number(a[1])),coreYear=a[2]):"Y-n-j"==b&&(a=a.split("-"),coreDay=SPC.Date.dateConverter.padZeroLeft(Number(a[2])),
coreMonth=SPC.Date.dateConverter.padZeroLeft(Number(a[1])),coreYear=a[0]);return coreYear+"-"+coreMonth+"-"+coreDay};SPC.Date.convertTime=function(a,b){var b=b||SPC.userPrefs.calendar.timeformat,d=new Date(a),c=d.getHours(),d=d.getMinutes();if("core"==b)return c=SPC.Date.dateConverter.padZeroLeft(c),d=SPC.Date.dateConverter.padZeroLeft(d),c+":"+d;var e="pm";12>c?(e="am",0==c&&(c=12)):12!=c&&(c-=12);return c+":"+SPC.Date.dateConverter.padZeroLeft(d)+e};SPC.Date.convertTimeFormat=function(a,b){var d=
new Date,c,e;if(/am|pm/.test(a)){c=a.match(/^(.*?)(am|pm)$/);var h=c[2];/:/.test(a)||(a=c[1]+":00"+c[2]);c=parseInt(a.split(":")[0]);e=parseInt(a.split(":")[1]);"am"==h?12==c&&(c=0):12!=c&&(c=Number(c)+12)}else c=Number(a.split(":")[0]),e=Number(a.split(":")[1]);d.setHours(c);d.setMinutes(e);d=d.getTime();b||(b=SPC.userPrefs.calendar.timeformat);return"core"==b?SPC.Date.convertTime(d,"core"):SPC.Date.convertTime(d,"standard")};SPC.Date.mktime=function(){for(var a=new Date,b="Hours Minutes Seconds Month Date FullYear".split(" "),
d=arguments,c=0;c<b.length;c++)"undefined"!==typeof d[c]&&("Month"==b[c]&&(month-=1),a["set"+b[c]](d[c]));return a.getTime()};SPC.Date.dateConverter.getEventType=function(a,b){return a==b?"standard":"multi_day"};SPC.Calendar.timeSlots={};(function(){var a,b;for(b=0;23>=b;b++)a=SPC.Date.dateConverter.padZeroLeft(b)+":00",SPC.Calendar.timeSlots[a]=SPC.Date.convertTimeFormat(a),a=SPC.Date.dateConverter.padZeroLeft(b)+":30",SPC.Calendar.timeSlots[a]=SPC.Date.convertTimeFormat(a)})();SPC.Date.parseDate=
function(a){return"string"===typeof a?(a=a.split("-"),{year:+a[0],month:+a[1],day:+a[2]}):{year:a.getFullYear(),month:a.getMonth()+1,day:a.getDate()}};SPC.parsedToday=SPC.Date.parseDate(SPC.today);SPC.Date.strToObj=function(a){a=SPC.Date.parseDate(a);return new Date(a.year,a.month-1,a.day,0,0,0)};SPC.Date.objToStr=function(a){var b=a.getFullYear(),d=SPC.Date.dateConverter.padZeroLeft(a.getMonth()+1),a=SPC.Date.dateConverter.padZeroLeft(a.getDate());return b+"-"+d+"-"+a};SPC.Date.addDate=function(a,
b,d){d=d?a:SPC.Date.parseDate(a);b=new Date(d.year,d.month-1,d.day+b);return a instanceof Date?b:SPC.Date.objToStr(b)};SPC.Date.getEndOfMonth=function(a,b){b||(a=SPC.Date.parseDate(a));return(new Date(a.year,a.month,0)).getDate()};SPC.Date.getStartDateOfMonth=function(a){"string"===typeof a&&(a=SPC.Date.parseDate(a));return SPC.Date.objToStr(new Date(a.year,a.month-1,1))};SPC.Date.getEndDateOfMonth=function(a){"string"===typeof a&&(a=SPC.Date.parseDate(a));return SPC.Date.objToStr(new Date(a.year,
a.month-1,this.getEndOfMonth(a,!0)))};SPC.Date.getStartDateOfWeek=function(a,b){a=a||SPC.currentDate;b=b||SPC.Calendar.START_DAY_OF_WEEK;"string"===typeof a&&(a=SPC.Date.strToObj(a));for(var d,c=6;0<=c;c--)if(d=SPC.Date.addDate(a,-c),d.getDay()==b)return SPC.Date.objToStr(d)};SPC.Date.getCalendarViewDates=function(a,b,d){if(!a)throw{msg:"Undefined View "+a};var b=b||SPC.currentDate,c=this.parseDate(b),e=[];if("day"==a||"staff"==a||"timeline"==a&&"day"==d)return[b];if("week"==a||"timeline"==a&&"week"==
d){b=this.getStartDateOfWeek(b);for(c=0;7>c;c++)e.push(this.addDate(b,c));return e}if("custom"==a){for(c=0;c<SPC.userPrefs.calendar.custom_view;c++)e.push(this.addDate(b,c));return e}if("month"==a){b=this.getStartDateOfWeek(new Date(c.year,c.month-1,1));a=this.objToStr(new Date(c.year,c.month,0));for(c=0;7>c;c++){for(var d=7*c,h=7*c+7;d<h;d++)e.push(this.addDate(b,d));if(e[e.length-1]>=a)break}return e}if("agenda"==a){for(c=0;60>=c;c++)e.push(this.addDate(b,c));return e}if("year"==a)return e=(new Date(c.year,
12,0)).getDate(),[c.year+"-01-01",c.year+"-12-"+e]};SPC.Date.getDayName=function(a,b,d){"number"!=typeof a&&("string"==typeof a&&(a=SPC.Date.strToObj(a)),a=a.getDay());return d?$.datepicker.regional[SPC.SYSTEM_LANGUAGE].dayNamesMin[a]:b?$.datepicker.regional[SPC.SYSTEM_LANGUAGE].dayNamesShort[a]:$.datepicker.regional[SPC.SYSTEM_LANGUAGE].dayNames[a]};SPC.Date.getMonthName=function(a,b){"string"==typeof a&&(a=SPC.Date.strToObj(a));var d=a.getMonth();return b?$.datepicker.regional[SPC.SYSTEM_LANGUAGE].monthNamesShort[d]:
$.datepicker.regional[SPC.SYSTEM_LANGUAGE].monthNames[d]};SPC.Date.getUserLongDate=function(a){"string"===typeof a&&(a=SPC.Date.strToObj(a));var b=SPC.userPrefs.calendar.longdate_format,d=SPC.Date.parseDate(a),c=d.day,d=d.year,e=SPC.Date.getDayName(a),a=SPC.Date.getMonthName(a,!0);switch(b){case "lit_end":return e+", "+c+" "+a+" "+d;case "mid_end":return e+", "+a+" "+c+", "+d;case "big_end":return d+"-"+a+"-"+c+", "+e}};SPC.Calendar.Event.getPublicEventDateTitle=function(a){var b=a.start_date,d=a.start_time,
c=a.end_date,e=a.end_time,a=SPC.Calendar.Event.getEventType(a),h,i,f,b=SPC.Date.getUserLongDate(b);h=SPC.Date.convertTimeFormat(d);i=SPC.Date.convertTimeFormat(e);f=b+", "+h+" - "+i;"all_day"==a?f=b+", "+SPC.translate("All day"):"multi_day"==a&&(c=SPC.Date.getUserLongDate(c),f="00:00"==d&&"00:00"==e?b+" - "+c:b+", "+h+" &ndash; "+c+", "+i);return f};SPC.Calendar.Event.Sort={};SPC.Calendar.Event.Sort.getTypePrecedence=function(a){return"multi_day"==a?-1:"all_day"==a?0:1};SPC.Calendar.Event.Sort.sortTime=
function(a,b){$t1=a.type;$t2=b.type;if("standard"==$t1&&"standard"==$t2)return a.start_time==b.start_time?0:a.start_time<b.start_time?-1:1;$t1=SPC.Calendar.Event.Sort.getTypePrecedence($t1);$t2=SPC.Calendar.Event.Sort.getTypePrecedence($t2);return $t1==$t2?0:$t1<$t2?-1:1};SPC.Calendar.Event.Sort.sortDate=function(a,b){var d=a.start_date.split("-"),c=a.start_time.split(":"),d=(new Date(d[0],d[1],d[2],parseInt(c[0],10),parseInt(c[1],10),0)).getTime(),c=b.start_date.split("-"),e=b.start_time.split(":"),
c=(new Date(c[0],c[1],c[2],parseInt(e[0],10),parseInt(e[1],10),0)).getTime();return d==c?0:d<c?-1:1};SPC.Calendar.Event.getEventType=function(a){var b="standard";a.start_date==a.end_date&&("00:00"==a.start_time&&"00:00"==a.end_time)&&(b="all_day");a.start_date!=a.end_date&&(b="multi_day");return b};SPC.Calendar.Event.getMultiDayEventSpan=function(a,b){var d=SPC.Date.strToObj(a).getTime()/1E3,c=SPC.Date.strToObj(b).getTime()/1E3;return parseInt((c-d)/86400,10)};SPC.Calendar.Event.Repeat={};SPC.Calendar.Event.Repeat.Events=
{};SPC.Calendar.Event.Repeat.addRepeatEvents=function(a,b,d){a.repeat.length&&SPC.Array.foreach(a.repeat,function(c,e){SPC.Calendar.Event.Repeat.Events[e.id]=$.extend({},e);SPC.Calendar.Event.Repeat.addRepeatEvents[e.repeat_type]({repeatEvent:e,events:a,rangeStartDate:b,rangeEndDate:d})})};SPC.Calendar.Event.Repeat.getDayOfMonthByWeek=function(a,b,d){for(var c,e=0,h=0;32>e&&!(c=SPC.Date.strToObj(SPC.Date.addDate(a,e)),c.getDay()==d&&h++,h==b);e++);return e+1};SPC.Calendar.Event.Repeat.addRepeatEvents.daily=
function(a){for(var b=a.repeatEvent,d=b.repeat_type,c=b.start_date,e=SPC.Date.parseDate(c),h=b.repeat_end_date,i=a.rangeStartDate,f=b.repeat_data,g=SPC.Calendar.Event.getEventType(b),j=+b.repeat_interval,l=a.weekly?1:j,p=+b.repeat_count,c="multi_day"==g?SPC.Calendar.Event.getMultiDayEventSpan(c,b.end_date):0,s=a.weekly?f.split(","):null,q=a.monthly?f.split(","):null,k=0,m,r=0,n,o;!(0!=p&&r==p);){if("daily"==d||"weekly"==d)b.start_date=SPC.Date.addDate(e,k,!0);a.monthly&&(n=e.month+k-1,o=e.day,""!=
f&&(o=SPC.Calendar.Event.Repeat.getDayOfMonthByWeek(new Date(e.year,n,1),+q[0],+q[1])),b.start_date=SPC.Date.objToStr(new Date(e.year,n,o)));a.yearly&&(b.start_date=SPC.Date.objToStr(new Date(e.year+k,e.month-1,e.day)));k+=l;a.weekly&&(m=SPC.Date.strToObj(b.start_date).getDay(),m==SPC.Calendar.endDayOfWeek&&(k+=7*(j-1)));if(!(a.weekly&&!1===SPC.Array.arraySearch(m,s)))if(r++,"standard"==g||"all_day"==g?b.end_date=b.start_date:"multi_day"==g&&(b.end_date=SPC.Date.addDate(b.start_date,c)),b.start_date<
i)"multi_day"==g&&b.end_date>=i&&SPC.Calendar.Event.Repeat.pushRepeatingEvent(b,g,a.events,c);else{if(b.start_date>h||b.start_date>a.rangeEndDate)break;SPC.Calendar.Event.Repeat.pushRepeatingEvent(b,g,a.events,c)}}};SPC.Calendar.Event.Repeat.addRepeatEvents.weekly=function(a){a.weekly=!0;SPC.Calendar.Event.Repeat.addRepeatEvents.daily(a)};SPC.Calendar.Event.Repeat.addRepeatEvents.monthly=function(a){a.monthly=!0;SPC.Calendar.Event.Repeat.addRepeatEvents.daily(a)};SPC.Calendar.Event.Repeat.addRepeatEvents.yearly=
function(a){a.yearly=!0;SPC.Calendar.Event.Repeat.addRepeatEvents.daily(a)};SPC.Calendar.Event.Repeat.pushRepeatingEvent=function(a,b,d,c){a=$.extend({},a);if("multi_day"!=b)d[b][a.start_date]||(d[b][a.start_date]=[]),d[b][a.start_date].push(a),d.all[a.start_date]||(d.all[a.start_date]=[]),d.all[a.start_date].push(a);else{d.multi_day.push(a);for(var b=0,e;b<=c;b++)e=SPC.Date.addDate(a.start_date,b),d.all[e]||(d.all[e]=[]),d.all[e].push(a)}};SPC.Calendar.Event.Repeat.getRepeatEventSummary=function(a){var b=
a.repeat_type,d=a.start_date,c=SPC.Date.parseDate(d),e=+a.repeat_interval,h=+a.repeat_count,i=a.repeat_data,a=a.repeat_end_date,f="9999-01-01"==a?SPC.translate("never"):SPC.Date.getUserLongDate(a),g="";switch(b){case "daily":g=SPC.translate("daily");1!=e&&(g=SPC.String.sprinf(SPC.translate("Every %s days"),[e]));break;case "weekly":var j=[];SPC.Array.foreach(i.split(","),function(a,b){j.push(SPC.Date.getDayName(+b))});j=j.join(", ");g=SPC.translate("weekly")+" ("+j+")";1!=e&&(g=SPC.String.sprinf(SPC.translate("Every %s weeks"),
[e])+" ("+j+")");break;case "monthly":g=SPC.translate("monthly")+", "+SPC.translate("day")+" "+c.day;break;case "yearly":g=SPC.translate("yearly")+" "+SPC.String.sprinf(SPC.translate("on %s %s",!1),[SPC.Date.getMonthName(d),c.day])}"9999-01-01"!=a&&(g+=" "+SPC.String.sprinf(SPC.translate("until %s"),[f]));0!=h&&(g+=", "+SPC.String.sprinf(SPC.translate("%s times"),[h]));return g};SPC.Calendar.getEvents=function(a,b,d,c){var e=b[0],h=SPC.Array.end(b);return $.ajax({data:{spcAppRequest:"calendar/event/getEvents",
params:[a,d,e,h]},success:function(d){var f=d.events,g;for(g in f)f[g]instanceof Array&&("repeat"!=g&&"multi_day"!=g)&&(f[g]={});SPC.Calendar.Event.Repeat.addRepeatEvents(f,e,h);SPC.Object.length(f.standard)&&SPC.Array.foreach(f.standard,function(a){f.standard[a].sort(SPC.Calendar.Event.Sort.sortDate)});if(SPC.Object.length(f.all)){var j=[],l={};SPC.Array.foreach(f.all,function(a){j.push(a)});j.sort();SPC.Array.foreach(j,function(a,b){l[b]=f.all[b]});f.all=l;SPC.Array.foreach(f.all,function(a){f.all[a].sort(SPC.Calendar.Event.Sort.sortTime)})}c&&
c(a,b,f)}})};SPC.setCookie=function(a,b,d,c){var e=[],c=c||"/";e.push(a+"="+encodeURIComponent(b));d&&(a=(new Date((new Date).getTime()+d)).toUTCString(),e.push("expires="+a));e.push("path="+c);document.cookie=e.join("; ")};SPC.getCookie=function(a){for(var b=document.cookie.split(";"),d={},c=[],e=0,h=b.length;e<h;e++)c=b[e].split("="),d[$.trim(c[0])]=decodeURIComponent(c[1]);return a?!d[a]?!1:d[a]:d};SPC.ns("SPC.Util.Form");SPC.Util.Form.getFormVals=function(a){var a=document.getElementById(a),b=
{},d,c;$("input[type='text'], textarea, select, :radio",a).each(function(){d=$(this);if(d.is(":radio")&&!this.checked)return!0;c=d.attr("name");b[c]=d.val()});var e={};$(":checkbox",a).each(function(){d=$(this);c=d.attr("name");e[c]||(e[c]=[]);e[c].push(d.val())});$.each(e,function(a,c){b[a]=c.join(",")});return b};SPC.Util.Form.validate=function(a,b,d){$("#spc-form-validator-style").length||$(document.body).prepend("<style>                             .spc-form-validator-info {                                font-size: 10px;                                color: #DD4B39;                                margin: 1px 0;                                position: absolute;                             }                         </style>");
var a=document.getElementById(a),c,e,h,i=!0;$(".spc-form-validator-info",a).remove();$(".spc-validate",a).each(function(){c=$(this);e=c.val();h=c.attr("data-spc-validate");switch(h){case "required":if(""==e)return"function"===typeof d?d(c,"This field is required!"):c.after("<div class='spc-form-validator-info'>                                            This field is required!                                        </div>"),i=!1}});return i};$.fn.elementIndex=function(){return $($(this).parent().find($(this)[0].tagName)).index(this)};
jQuery.expr[":"].textEquals=function(a,b,d){return $(a).text()==d[3]};$.fn.spcPlaceholder=function(){this.each(function(){var a=$(this);a.focus(function(){a.val()==a.attr("data-spc-placeholder-text")&&a.val("").css({color:"#333"})}).blur(function(){""==a.val()&&a.val(a.attr("data-spc-placeholder-text")).css({color:"#777"})}).css({color:"#777"})})};$(".spc-placeholder").spcPlaceholder();$(".spc-btn-group").find("input, button").addClass("spc-btn ui-widget ui-corner-all ui-state-default ui-button");
$.ui&&(SPC.jQueryUI={},$.ui.dialog.prototype.options.resizable=!1,$.ui.dialog.prototype.options.modal=!0,$.ui.dialog.prototype.options.autoOpen=!1,$.ui.dialog.prototype.options.width="auto",$.ui.dialog.prototype.options.height="auto",$(".jq-ui-button").button(),$(".jq-ui-buttonset").buttonset(),SPC.jQueryUI.getActiveDialog=function(){this.$dialogs||(this.$dialogs=$(".ui-dialog-content"));var a=[];this.$dialogs.each(function(){$(this).dialog("isOpen")&&a.push($(this))});a.sort(function(a,d){var c=
+a.closest(".ui-dialog").css("z-index"),e=+d.closest(".ui-dialog").css("z-index");return c==e?0:c>e?1:-1});return a.pop()},$(".ui-resizable-handle").live("mousedown",function(){$.ui.curResizeDirection=this.className.split("-").pop()}),$(".ui-btn").button());(function(){function a(a){var b=a||window.event,d=[].slice.call(arguments,1),i=0,f=0,g=0,a=$.event.fix(b);a.type="mousewheel";b.wheelDelta&&(i=b.wheelDelta/120);b.detail&&(i=-b.detail/3);g=i;if(b.axis!==void 0&&b.axis===b.HORIZONTAL_AXIS){g=0;
f=-1*i}b.wheelDeltaY!==void 0&&(g=b.wheelDeltaY/120);b.wheelDeltaX!==void 0&&(f=-1*b.wheelDeltaX/120);d.unshift(a,i,f,g);return($.event.dispatch||$.event.handle).apply(this,d)}var b=["DOMMouseScroll","mousewheel"];if($.event.fixHooks)for(var d=b.length;d;)$.event.fixHooks[b[--d]]=$.event.mouseHooks;$.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var c=b.length;c;)this.addEventListener(b[--c],a,false);else this.onmousewheel=a},teardown:function(){if(this.removeEventListener)for(var c=
b.length;c;)this.removeEventListener(b[--c],a,false);else this.onmousewheel=null}};$.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})();(function(){function a(a){if(typeof a.data==="string"){var d=a.handler,c=a.data.toLowerCase().split(" ");a.handler=function(a){if(!(this!==a.target&&(/textarea|select/i.test(a.target.nodeName)||a.target.type==="text"||a.target.type==="password"))){var b=
a.type!=="keypress"&&jQuery.hotkeys.specialKeys[a.which],i=String.fromCharCode(a.which).toLowerCase(),f="",g={};a.altKey&&b!=="alt"&&(f=f+"alt+");a.ctrlKey&&b!=="ctrl"&&(f=f+"ctrl+");a.metaKey&&(!a.ctrlKey&&b!=="meta")&&(f=f+"meta+");a.shiftKey&&b!=="shift"&&(f=f+"shift+");if(b)g[f+b]=true;else{g[f+i]=true;g[f+jQuery.hotkeys.shiftNums[i]]=true;f==="shift+"&&(g[jQuery.hotkeys.shiftNums[i]]=true)}b=0;for(i=c.length;b<i;b++)if(g[c[b]])return d.apply(this,arguments)}}}}jQuery.hotkeys={version:"0.8",specialKeys:{8:"backspace",
9:"tab",13:"return",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"capslock",27:"esc",32:"space",33:"pageup",34:"pagedown",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"del",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",106:"*",107:"+",109:"-",110:".",111:"/",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",144:"numlock",145:"scroll",191:"/",224:"meta"},shiftNums:{"`":"~",1:"!",2:"@",
3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(","0":")","-":"_","=":"+",";":": ","'":'"',",":"<",".":">","/":"?","\\":"|"}};jQuery.each(["keydown","keyup","keypress"],function(){jQuery.event.special[this]={add:a}})})()});
